### ISSUE TITLE
Varnish 4.0

### ISSUE THREAD

**Issue by bastttttt** [wikimedia/varnishkafka#4]
There is a way to use varnishkafka with varnish 4.x?

**Comment by elukey** [comment]
Hi! Not at the moment because the Varnish API changed a lot from 3 to 4, but we are porting the code. I'll update you as soon as I'll have some good news :)

**Comment by bastttttt** [comment]
nice :) thanks

**Comment by elukey** [comment]
Forgot to update this contact, but varnishkafka now fully supports Varnish 4!

**Comment by bastttttt** [comment]
Very good job! Thank you
