### ISSUE TITLE
Note: Starts reading at the tail of the Varnish log

### ISSUE THREAD

**Issue by xordspar0** [wikimedia/varnishkafka#58]
I was curious about this, so I looked it up in the source code. The following lines show that the initial position of the Varnish log cursor is at the tail:

```c
if (conf.vsm != NULL && !VSM_IsOpen(conf.vsm)) {
	if (varnish_api_open_handles(&conf.vsm, &conf.vsl, &vsl_cursor,
				     VSL_COPT_TAIL | VSL_COPT_BATCH, &conf.vslq,
				     conf.q_flag_query) == -1) {
		nanosleep(&duration_100ms, NULL);
		continue;
	} else {
		vk_log("VSLQ_Dispatch", LOG_ERR, "Log acquired!");
```

The implication of this is that varnishkafka only collects log entries that occur while it is running. This is fine for our purposes, but it's something I had to dig into the source code to find out for sure.

**Comment by elukey** [comment]
Hi! Do you think that a doc upgrade would be enough, or do you have more ideas about that bit of code?

**Comment by xordspar0** [comment]
A note in the docs would be great!

**Comment by elukey** [comment]
@xordspar0 sorry for the delay, let me know if the notes are good enough!

**Comment by xordspar0** [comment]
Looks great. Thanks for you attention to this.
