### ISSUE TITLE
What is the future of varnishkafka?

### ISSUE THREAD

**Issue by dabelenda** [wikimedia/varnishkafka#62]
I can see on https://phabricator.wikimedia.org that you are dropping varnish in favor of apache traffic server. So I was wondering what will happend with varnishkafka.

**Comment by elukey** [comment]
Hi @dabelenda, we'll likely move from varnishkafka to atskafka during the next months, but it will take a while. In the meantime, we tested it with Varnish 6 and everything works as expected, and  there are no outstanding bugs reported.

Ideally in the long term we'll maintain this software as best effort, merging community patches if needed :)

**Comment by dabelenda** [comment]
Ok, so the project will not be archived, and will continue to live even if only from community work. Good to know.

We use varnishkafka in production since a few years back now, and have no issues either. Varnish 6 support was contributed by me (my nick in your gerrit instance is a pseudo-random string so I don't expect anyone to realize it), and we've been using it since then without issues.

**Comment by elukey** [comment]
My bad, I completely forgot about your work sorry, too many nicks in github :)

I am not sure about the very long term but I'd say that for the next couple of years we'll not archive it, but in case it should be pretty easy to fork and continuing the work. Ideally this codebase should be rewritten from scratch to be more maintainable and testable, but it needs time.

**Comment by dabelenda** [comment]
No problem, as I wrote, I didn't expect anyone to remember the full git history or the talks we've had on gerrit where my nick is not even the same. 

If the situation changes, probably that somebody in this org https://github.com/camptocamp (if I am not working for them anymore) will be willing to take ownership of the project. You can contact me if you want to arrange a smooth transition.
